### PR TITLE
ESP32-S2 support

### PR DESCRIPTION
**Pull request by Ebiroll**
I did not completely understand the naming of the sections.

### CODE REVIEW

**Comment by tslater2006** [comment]
Re: naming of the sections are you refering to DROM0, DROM1 etc?

**Comment by Ebiroll** [comment]
Yes. I just noticed that the section name must start with "I" in order to be marked as Code. I must fix that.

**Comment by Ebiroll** [comment]
OK. That has been fixed. For naming of the sections I tried to use the names from Address Mapping chapter (1.3.1) in the technical reference manual.  The externally mapped memory i call IF_TEXT and F_DATA, as it is mapped to flash when loaded.

**Comment by tslater2006** [comment]
Thank you for adding this support to the loader!

**Pull request merged**
